[colors]
background       = '#e4e7e7'
foreground       = '#181b1a'
cursor           = '#181b1a'
vi-cursor        = '#007564'

black            = '#c3cac9'
red              = '#cf0040'
green            = '#007564'
yellow           = '#007907'
blue             = '#6c6b04'
magenta          = '#007564'
cyan             = '#127813'
white            = '#181b1a'

dim-foreground   = '#181b1a'
dim-black        = '#c3cac9'
dim-red          = '#cf0040'
dim-green        = '#007564'
dim-yellow       = '#007907'
dim-blue         = '#6c6b04'
dim-magenta      = '#007564'
dim-cyan         = '#127813'
dim-white        = '#181b1a'

light-foreground = '#181b1a'
light-black      = '#618c86'
light-red        = '#cf0040'
light-green      = '#007564'
light-yellow     = '#007907'
light-blue       = '#6c6b04'
light-magenta    = '#007564'
light-cyan       = '#127813'
light-white      = '#181b1a'

tabs             = '#c3cac9'
tabs-active      = '#007564'
bar              = '#181b1a'
split            = '#c3cac9'

# Search
search-match-background          = '#6c6b04'
search-match-foreground          = '#c3cac9'
search-focused-match-background  = '#007564'
search-focused-match-foreground  = '#c3cac9'

# Hints
hint-foreground  = '#c3cac9'
hint-background  = '#007907'

# Selection
selection-foreground = '#4e5655'
selection-background = '#c3cac9'
