[colors]
ansi = [
    "#dae5e2",
    "#ba1a1a",
    "#006a63",
    "#4a6360",
    "#47617a",
    "#81d5cc",
    "#b1ccc8",
    "#161d1c",
]
background = "#f4fbf9"
brights = [
    "#6f7977",
    "#ba1a1a",
    "#006a63",
    "#4a6360",
    "#47617a",
    "#81d5cc",
    "#b1ccc8",
    "#161d1c",
]
compose_cursor = "#161d1c"
cursor_bg = "#161d1c"
cursor_border = "#161d1c"
cursor_fg = "#f4fbf9"
foreground = "#161d1c"
scrollbar_thumb = "#dae5e2"
selection_bg = "#dae5e2"
selection_fg = "#3f4947"
split = "#6f7977"
visual_bell = "#dae5e2"

[colors.indexed]
16 = "#4a6360"
17 = "#161d1c"

[colors.tab_bar]
background = "#f4fbf9"
inactive_tab_edge = "#dae5e2"

[colors.tab_bar.active_tab]
bg_color = "#006a63"
fg_color = "#ffffff"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#f4fbf9"
fg_color = "#161d1c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#f4fbf9"
fg_color = "#161d1c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#dae5e2"
fg_color = "#161d1c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#6f7977"
fg_color = "#161d1c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
